### ISSUE TITLE
TemplateDoesNotExist: datetimepicker/div.html

### ISSUE THREAD

**Issue by nkgilley** [escodebar/django-datetimepicker#9]
When I install version 3.14 via pip and follow the setup instructions I run into the following exception when I run the server:

`django.template.exceptions.TemplateDoesNotExist: datetimepicker/div.html`

I also notice there isn't a templates or static directory where pip installed it:
```
(datetimepicker) [nolan@Arch sample]$ ls ~/virtualenvs/datetimepicker/lib/python3.6/site-packages/datetimepicker/
helpers.py  __init__.py  __pycache__  urls.py  views.py  widgets.py
```

**Comment by FadedCoder** [comment]
Any fix for this @nkgilley ?

**Comment by ericw13** [comment]
@FadedCoder The files are in this repo under the datetimepicker directory. I was able to get this to work with a couple sym links:

Replace $REPO_ROOT with the top level directory where you cloned this repo:

cd $REPO_ROOT/sample/sample/templates
ln -s $REPO_ROOT/datetimepicker/templates/datetimepicker datetimepicker
cd $REPO_ROOT/sample/sample
ln -s $REPO_ROOT/datetimepicker/static static

Restart the server and this should work.
